local ADDON_NAME, namespace = ... 	--localization
local L = namespace.L 				--localization

--local LOCALE = GetLocale()

if namespace.locale == "ruRU" then
	-- The EU English game client also
	-- uses the US English locale code.

-- ###########################################################################################################
-- ##	русский (Russian) translations provided by Nappsel, Wishko, berufegoru, and n1mrorox on Curseforge. ##
-- ###########################################################################################################

L["  /dcstats config: Opens the DejaCharacterStats addon config menu."] = "/dcstats config: Открывает настройки дополнения DejaCharacterStats."
--Translation missing 
-- L["  /dcstats reset:  Resets DejaCharacterStats options to default."] = ""
--Translation missing 
-- L["%s of %s increases %s by %.2f%%"] = ""
L["/dcstats reset:  Resets DejaCharacterStats frames to default positions."] = "/dcstats reset: Сбрасывает DejaCharacterStats до настроек по умолчанию."
L["About DCS"] = "Около DCS"
L["Agility"] = "Ловкость"
L["All Stats"] = "Все"
L["Armor"] = "Броня"
L["Attack"] = "Атакующие"
L["Attack Power"] = "Сила атаки"
L["Attack Speed"] = "Скорость атаки"
L["Average Durability"] = "Средняя прочность"
L["Average equipped item durability percentage."] = "Средняя прочность экипированных предметов в процентах."
L["Average Item Level:"] = "Средний уровень предметов"
L["Avoidance"] = "Уклонение"
L["Avoidance Rating"] = "Показатель избегания"
L["Blizzard's Hide At Zero"] = "Blizzard скрытие при нуле"
L["Block"] = "Блок"
L["Character Stats:"] = "Характеристики персонажа"
L["Checked displays all stats. Unchecked displays relevant stats. Use Shift-scroll to snap to the top or bottom."] = "Если отмечено, то отображаются все характеристики. Если нет, то только используемые персонажем. Используйте Shift + колёсико, чтобы быстро переместиться вверх или вниз списка."
L["Class Colors"] = "Цвета классов"
L["Class Crest Background"] = "Фон с гербом класса"
L["Critical Strike Rating"] = "Показатель критического удара"
L["Damage"] = "Урон"
L["DCS's Hide At Zero"] = "DCS скрытие при нуле"
L["Decimals"] = "Десятичные числа"
L["Defense"] = "Защитные"
L["DejaCharacterStats is currently using"] = "DejaCharacterStats уже используется"
L["DejaCharacterStats Slash commands (/dcstats):"] = "DejaCharacterStats Slash команды (/dcstats):"
L["Direct table"] = "Прямая таблица"
L["Displays \"Enhancements\" category stats to two decimal places."] = "Отображает \"расширенные\" характеристики персонажа используя десятичные числа."
L["Displays a durability bar next to each item."] = "Отображает индикатор прочности рядом с каждым предметом."
L["Displays average item durability on the character shirt slot and durability frames."] = "Отображает среднюю прочность предметов в слоте рубашки персонажа и окне прочности."
L["Displays average item level to one decimal place."] = "Отображать средний уровень предметов используя одно число после точки."
--Translation missing 
-- L["Displays average item level to two decimal places."] = ""
L["Displays average item level with class colors."] = "Отображать средний уровень предметов цветом класса."
L["Displays each equipped item's durability."] = "Отображает прочность каждого экипированного предмета."
L["Displays each equipped item's repair cost."] = "Отображает стоимость ремонта каждого экипированного предмета."
L["Displays Equipped/Available item levels unless equal."] = "Отображает уровень Надетых/Доступных предметов, если значения не равны."
L["Displays the average Durability percentage for equipped items in the stat frame."] = "Показывать средний процент Прочности для экипированных предметов в окне характеристик."
L["Displays the class crest background."] = "Отображать фон с гербом класса."
L["Displays the DCS scrollbar."] = "Отображать полосу прокрутки DCS."
L["Displays the Expand button for the character stats frame."] = "Отображает кнопку скрывающую окно характеристик персонажа."
L["Displays the item level of each equipped item."] = "Отображать уровень каждого надетого предмета."
L["Displays the Repair Total before discounts for equipped items in the stat frame."] = "Отображает стоимость ремонта без учёта скидок на экипированные предметы в окне характеристик персонажа."
L["Dodge Rating"] = "Показатель уклонения"
L["Durability"] = "Прочность"
L["Durability Bars"] = "Индикатор прочности"
L["Energy Regen"] = "Восполнение энергии"
L["Equipped/Available"] = "Надето/Доступно"
L["Expand"] = "Кнопка \"Скрыть\""
L["Focus Regen"] = "Восстановление концентрации"
L["General"] = "Основные"
L["General global cooldown for casters. Individual spells, set bonuses, talents, etc. not considered. Not suitable for melee. Improvements coming Soon(TM)."] = "Общее время восстановления(GCD) для кастеров. Индивидуальные заклинания, бонусы комплектов, таланты и т.д., не рассматриваются. Не подходит для ближнего боя. Улучшения в ближайшее время (TM)."
L["General global cooldown refresh time."] = "Основное время общего восстановления."
L["Global Cooldown"] = "Общее время восст."
L["Haste"] = "Скорость"
L["Haste Rating"] = "Показатель скорости"
L["Hide Character Stats"] = "Скрыть характеристики персонажа"
L["Hides \"Enhancements\" stats if their displayed value would be zero. Checking \"Decimals\" changes the displayed value."] = "Скрыть характеристики \"Улучшений\" если их значение равно нулю. Выбор \"Десятичных чисел\" изменяет отображаемое значение."
L["Hides \"Enhancements\" stats only if their numerical value is exactly zero. For example, if stat value is 0.001%, then it would be displayed as 0%."] = "Скрыть характеристики \"Улучшений\" только если их значение равно нулю. Например, если значение характеристики равно 0.001%, то оно будет отображаться как 0%."
L["Ilvl Decimals"] = "Десятичные числа для ilvl"
L["Item Durability"] = "Прочность предмета"
L["Item Level"] = "Уровень предмета"
L["Item Level 1 Decimal Place"] = "Уровень предметов с десятичными"
L["Item Level 2 Decimal Places"] = "Уровень предметов с сотыми"
L["Item Repair Cost"] = "Стоимость ремонта предмета"
L["Item Slots:"] = "Ячейки снаряжения:"
L["kbytes of memory"] = "кбайт памяти"
L["kbytes of memory after garbage collection"] = "кбайт памяти после уборки \"мусора\""
L["Leech"] = "Cамоисцеление"
L["Leech Rating"] = "Показатель самоисцеления"
L["Lock DCS"] = "Заблокировать DCS"
L["Main Hand"] = "Правая рука"
L["Mana Regen"] = "Восполнение маны"
L["Mastery"] = "Искусность"
L["Mastery Rating"] = "Показатель искусности"
L["Miscellaneous:"] = "Разное:"
L["Movement Speed"] = "Скорость движения"
L["Off Hand"] = "Левая рука"
L["Offense"] = "нападение"
--Translation missing 
-- L["One Decimal Place"] = ""
L["Parry"] = "Парирование"
L["Parry Rating"] = "Показатель парирования"
L["Rating"] = "Показатели"
L["Ratings"] = "Показатели"
L["Relevant Stats"] = "специализация"
L["Repair Total"] = "Стоимость ремонта"
L["Requires Level "] = "Требуется уровень "
L["reset"] = "reset"
L["Reset Stats"] = "Сбросить хар-ки"
L["Reset to Default"] = "Сбросить настройки"
--Translation missing 
-- L["Resets order of stats."] = ""
L["Resetting config to defaults."] = "Сброс конфигурации по умолчанию."
L["Rune Speed"] = "Восст. рун"
L["Scrollbar"] = "Скроллбар"
L["Select which stats to display. Use Shift-scroll to snap to the top or bottom."] = "Выберите какие характеристики должны отображаться. Используйте Shift+Колёсико, чтобы быстро перемещаться к верхней или нижней части."
L["Select-A-Stat™"] = "Выбор характеристик"
L["Show all stats."] = "Показать все характеристики"
L["Show Character Stats"] = "Показать характеристики персонажа"
--Translation missing 
-- L["Show only stats relevant to your class spec."] = ""
L["Spell Power"] = "Сила заклинаний"
L["Total equipped item repair cost before discounts."] = "Общая стоимость ремонта без учёта скидок."
L["Two Decimal Places"] = "Два десятичных знака"
L["Unlock DCS"] = "Разблокировать DCS"
L["Versatility"] = "Универсальность"
L["Versatility Rating"] = "Показатель универсальности"
L["weapon auto attack (white) DPS."] = "Автоматическая атака оружием. \"Белый\" урон."
L["Weapon DPS"] = "Урон оружия"
L["With defaults"] = "С конфигурацией по умолчанию"

return end
