--local ADDON_NAME, namespace = ... 	--localization
local ADDON_NAME, namespace = ... 	--localization
local L = namespace.L 				--localization

--local LOCALE = GetLocale()
--print("at deDE",namespace.locale)
if namespace.locale == "deDE" then
	-- The EU English game client also
	-- uses the US English locale code.

-- #######################################################################################################################
-- ##	Deutsche (German) translations provided by pas06, flow0284, Markurion, Branduril, and NekoNyaaaa on Curseforge.	##
-- #######################################################################################################################

L["  /dcstats config: Opens the DejaCharacterStats addon config menu."] = "  /dcstats config: Öffnet das DejaCharacterStats Konfigurationsfenster."
L["  /dcstats reset:  Resets DejaCharacterStats options to default."] = "  /dcstats reset: Setzt DejaCharacterStats zurück."
L["%s of %s increases %s by %.2f%%"] = "%s von %s erhöht die %s um %.2f%%."
L["/dcstats reset:  Resets DejaCharacterStats frames to default positions."] = "/dcstats reset: Setzt DejaCharacterStats zurück."
L["About DCS"] = "Über DCS"
L["Agility"] = "Beweglichkeit"
L["All Stats"] = "Alle Statistiken"
L["Armor"] = "Rüstung"
L["Attack"] = "Angriff"
L["Attack Power"] = "Angriffskraft"
L["Attack Speed"] = "Angriffstempo"
L["Average Durability"] = "Durchschnittliche Haltbarkeit"
L["Average equipped item durability percentage."] = "Prozentuale Haltbarkeit der angelegten Gegenstände."
L["Average Item Level:"] = "Durchschnittliches Gegenstandslevel"
L["Avoidance"] = "Vermeidung"
L["Avoidance Rating"] = "Vermeidungsbewertung"
L["Blizzard's Hide At Zero"] = "Blizzard Verstecken bei Null"
L["Block"] = "Blocken"
L["Character Stats:"] = "Charakterwerte"
L["Checked displays all stats. Unchecked displays relevant stats. Use Shift-scroll to snap to the top or bottom."] = "Wenn ausgewählt, werden alle Werte gezeigt. Ansonsten nur die relevanten. Halte die Umschalttaste und scrolle, um direkt an den Anfang oder ans Ende zu springen."
L["Class Colors"] = "Klassenfarben"
L["Class Crest Background"] = "Klassenwappen Hintergrund"
L["Critical Strike Rating"] = "Kritische Trefferwertung"
L["Damage"] = "Schaden"
L["DCS's Hide At Zero"] = "DCS Verstecken bei Null"
L["Decimals"] = "Nachkommastellen"
L["Defense"] = "Verteidigung"
L["DejaCharacterStats is currently using"] = "DejaCharacterStats benutzt zurzeit"
L["DejaCharacterStats Slash commands (/dcstats):"] = "DejaCharacterStats Slashbefehle (/dcstats):"
L["Direct table"] = "Direktes Verzeichnes"
L["Displays \"Enhancements\" category stats to two decimal places."] = "Zeigt die Werte in der Kategorie Verstärkungen mit 2 Nachkommastellen an."
L["Displays a durability bar next to each item."] = "Zeigt neben jedem Gegenstand eine Haltbarkeitsleiste an."
L["Displays average item durability on the character shirt slot and durability frames."] = "Zeigt die durchschnittliche Haltbarkeit im Hemdplatz und in der Liste unter Haltbarkeit an."
L["Displays average item level to one decimal place."] = "Zeigt die durchschnittliche Gegenstandsstufe mit einer Nachkommastelle an."
L["Displays average item level to two decimal places."] = "Zeigt die durchschnittliche Elementebene mit zwei Nachkommastellen an."
L["Displays average item level with class colors."] = "Zeigt das durchschnittliche Gegenstandslevel mit der Klassenfarbe an."
L["Displays each equipped item's durability."] = "Zeigt die Haltbarkeit von jedem ausgerüsteten Gegenstand an."
L["Displays each equipped item's repair cost."] = "Zeigt die Reparaturkosten von jedem ausgerüsteten Gegenstand an."
L["Displays Equipped/Available item levels unless equal."] = "Zeigt die durchschnittliche Gegenstandsstufe von angelegten und verfügbaren Gegenständen an, wenn diese nicht gleich sind."
L["Displays the average Durability percentage for equipped items in the stat frame."] = "Zeigt die durchschnittliche Haltbarkeit in Prozent für die ausgerüsteten Gegenstände in der Charakterinfo an."
L["Displays the class crest background."] = "Zeigt den Klassenwappen Hintergrund an."
L["Displays the DCS scrollbar."] = "Zeigt den DCS Scrollbalken."
L["Displays the Expand button for the character stats frame."] = "Zeigt die Erweiterungsschaltfläche für die Charakterwerte an. "
L["Displays the item level of each equipped item."] = "Zeigt das Gegenstandslevel jedes angelegten Gegenstandes."
L["Displays the Repair Total before discounts for equipped items in the stat frame."] = "Zeigt die gesamten Reparaturkosten ohne Bonus für die ausgerüsteten Gegenstände in der Charakterinfo an."
L["Dodge Rating"] = "Ausweichwertung"
L["Durability"] = "Haltbarkeit"
L["Durability Bars"] = "Haltbarkeitsleisten"
L["Energy Regen"] = "Energieregeneration"
L["Equipped/Available"] = "Ausgerüstet/Verfügbar"
L["Expand"] = "Erweitern"
L["Focus Regen"] = "Fokusregeneration"
L["General"] = "Allgemein"
L["General global cooldown for casters. Individual spells, set bonuses, talents, etc. not considered. Not suitable for melee. Improvements coming Soon(TM)."] = "Allgemeine Abklingzeit für Zauberer. Individuelle Zauber, Rüstungsboni, Talente usw. werden nicht berücksichtigt. Nicht für Nahkämpfer geeignet. Verbesserungen kommen bald(TM)."
L["General global cooldown refresh time."] = "Allgemeine Abklingzeit."
L["Global Cooldown"] = "Globale Abklingzeit"
L["Haste"] = "Tempo"
L["Haste Rating"] = "Tempowertung"
L["Hide Character Stats"] = "Versteckt die Charakterwerte"
L["Hides \"Enhancements\" stats if their displayed value would be zero. Checking \"Decimals\" changes the displayed value."] = "Blendet \"Verbesserungen\" Statistiken aus,wenn ihr angezeigter Wert gleich Null wäre. \"Dezimalstellen\" auswählen verändert den angezeigten Wert."
L["Hides \"Enhancements\" stats only if their numerical value is exactly zero. For example, if stat value is 0.001%, then it would be displayed as 0%."] = "Blendet \"Verbesserungen\" Statistiken nur aus,wenn ihr numerischer Wert genau Null ist. Zum Beispiel,wenn der Wert 0,001% ist,dann würde er als 0% angezeigt werden."
L["Ilvl Decimals"] = "Nachkommastellen ilvl"
L["Item Durability"] = "Gegenstandshaltbarkeit"
L["Item Level"] = "Gegenstandslevel"
L["Item Level 1 Decimal Place"] = "Gegenstandsstufe mit 1 Nachkommastelle"
L["Item Level 2 Decimal Places"] = "Gegenstandsstufe mit 2 Nachkommastellen"
L["Item Repair Cost"] = "Gegenstandsreparaturkosten"
L["Item Slots:"] = "Gegenstandsfächer:"
L["kbytes of memory"] = "Kilobyte Arbeitsspeicher"
L["kbytes of memory after garbage collection"] = "Kilobyte Arbeitsspeicher nach der Speicherbereinigung"
L["Leech"] = "Lebensraub"
L["Leech Rating"] = "Lebensraubwertung"
L["Lock DCS"] = "DCS sperren"
L["Main Hand"] = "Waffenhand"
L["Mana Regen"] = "Manaregeneration"
L["Mastery"] = "Meisterschaft"
L["Mastery Rating"] = "Meisterschaftswertung"
L["Miscellaneous:"] = "Sonstiges:"
L["Movement Speed"] = "Lauftempo"
L["Off Hand"] = "Schildhand"
L["Offense"] = "Angriff"
L["One Decimal Place"] = "Einer Nachkommastelle"
L["Parry"] = "Ausweichen"
L["Parry Rating"] = "Parrierwertung"
L["Rating"] = "Wertung"
L["Ratings"] = "Bewertungen"
L["Relevant Stats"] = "Relevante Werte"
L["Repair Total"] = "Ges. Reparaturkosten"
L["Requires Level "] = "Benötigt Stufe "
L["reset"] = "reset"
L["Reset Stats"] = "Werte zurücksetzen"
L["Reset to Default"] = "Standardeinstellungen"
L["Resets order of stats."] = "Setzt die Reihenfolge der Statistiken zurück."
L["Resetting config to defaults."] = "Einstellungen zurücksetzen."
L["Rune Speed"] = "Runentempo"
L["Scrollbar"] = "Scrollbalken"
L["Select which stats to display. Use Shift-scroll to snap to the top or bottom."] = "Wähle die anzuzeigenden Werte aus. Halte die Umschalttaste und scrolle, um direkt an den Anfang oder ans Ende zu springen."
L["Select-A-Stat™"] = "Select-A-Stat™"
L["Show all stats."] = "Alle Werte anzeigen."
L["Show Character Stats"] = "Zeigt die Charakterwerte"
L["Show only stats relevant to your class spec."] = "Zeigen Sie nur Statistiken an, die für Ihre Klassenspezifikation relevant sind."
L["Spell Power"] = "Zaubermacht"
L["Total equipped item repair cost before discounts."] = "Reparaturkosten für angelegte Gegenstände ohne Abzug von Rabatt."
L["Two Decimal Places"] = "Zwei Dezimalstellen"
L["Unlock DCS"] = "DCS freischalten"
L["Versatility"] = "Vielseitigkeit"
L["Versatility Rating"] = "Vielseitigkeitswertung"
L["weapon auto attack (white) DPS."] = "Schaden pro Sekunde der automatischen (weißen) Waffenangriffe."
L["Weapon DPS"] = "Waffen-SPS"
L["With defaults"] = "Mit Standardeinstellungen"

return end